### ISSUE TITLE
Jump/fall animation doesn't play if you change direction

### ISSUE THREAD

**Issue by KeirMcCulloch** [OS-Games-Official/Game#1]
Version: 
v0.0.3

To reproduce: 
While walking, hit the jump key and then immediately change direction. The jumping and falling animation will no longer play and then character will move through the air rigid.

Screenshot:
![Screenshot (942)](https://user-images.githubusercontent.com/59693282/95000561-ec828f00-05b9-11eb-9d31-37c24aff3d4f.png)

**Comment by EvilSquirrelGuy** [comment]
This was as easy as removing an animation rule but I tried to re-write the controlling script, that went well...
