### ISSUE TITLE
Player flies into the air if you walk into the tree stump/other obstacles

### ISSUE THREAD

**Issue by KeirMcCulloch** [OS-Games-Official/Game#2]
Version:
v0.0.3

To reproduce:
Walk into any obstacle, the tree stump provides the greatest effect, and keep walking forwards even after you are over it. This sends you into the air, with larger objects sending you higher. No falling animation plays.

Screenshot:
![Screenshot (946)](https://user-images.githubusercontent.com/59693282/95000658-a417a100-05ba-11eb-8aac-f4731b6ecbfd.png)

**Comment by EvilSquirrelGuy** [comment]
Done by changing hitboxes, I also shrunk the stump (quite significantly)
